### ISSUE TITLE
Can't Open Labs with 'Learn Open' in Terminal

### ISSUE THREAD

**Issue by kclunie** [learn-co-curriculum/rails-intro-to-rest#10]
Learn is getting stuck on my old labs and not automatically opening to the next lab that is due. Therefore I also cannot use "learn open" in my local terminal to open the next lab. This used to work fine.

**Comment by jenmyers** [comment]
I'm having difficulty reproducing the issue, so I'm going to close it for now. This might have been a local environment problem.
