### ISSUE TITLE
Extra "how" in a sentence above the diagram.

### ISSUE THREAD

**Issue by Lukas-Roberts** [learn-co-curriculum/rails-intro-to-rest#11]
Sentence reads Here is a diagram that shows how **how** the views, controller actions, routes, and HTTP verbs are all mapped together:" You just need to remove the extra "how."

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
