### ISSUE TITLE
Diagram is a bit confusing

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/rails-intro-to-rest#2]
So many boxes!

I would merge the HTTP verb and the HTTP path section into one. Maybe other ways? I dunno it just seems like there is a lot going on

**Comment by pletcher** [comment]
Fixed https://github.com/learn-co-curriculum/rails-intro-to-rest/commit/dd5065c0bff0a300aa146e29c172e5fd97f5e830?
